
genWeightsFromNRooTracker_testinp0dnue: genWeightsFromNRooTracker_testinp0dnue.cxx
	g++ $< -o $@ --std=c++11 `t2kreweight-config --cflags` `t2kreweight-config --linkflags` `t2kreweight-config --nd280flags` `t2kreweight-config --niwgflags` `t2kreweight-config --neutflags` `t2kreweight-config --neutexeflags` `t2kreweight-config --rootflags`